spring:
  application:
    name: scm-auth
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:18848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        enabled: true
        server-addr: 127.0.0.1:18848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        file-extension: yaml
        import-check:
          enabled: false
auth:
  jwt:
    issuer: scm-auth
    secret: change-this-dev-secret-key-at-least-32-bytes
    expire-seconds: 7200
  demo-user:
    username: admin
    password: admin123
    tenant-id: 1
    user-id: 10001
    roles: ROLE_ADMIN,ROLE_TENANT_ADMIN
server:
  port: 18086
