spring:
  application:
    name: scm-inventory
  config:
    import: "optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scm_inventory?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:18848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        enabled: true
        server-addr: 127.0.0.1:18848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        file-extension: yaml
        import-check:
          enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: UTF-8
server:
  port: 18084
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
knife4j:
  enable: true
integration:
  mdm:
    base-url: http://127.0.0.1:18082
mq:
  topics:
    order-ship-requested: order.ship.requested.v1
    order-cancel-requested: order.cancel.requested.v1
    inventory-ship-result: inventory.ship.result.v1
    inventory-cancel-result: inventory.cancel.result.v1
    sales-order-dlq: sales.order.requested.dlq.v1
  consumer-groups:
    inventory-order: scm-inventory-order-consumer
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
